### PR TITLE
Addresses Issue #11

### PR DESCRIPTION
**Pull request by michael-barlow3**
Added some changes to the python code to better display acronyms with multiple definitions.

### CODE REVIEW

**Comment by michael-barlow3** [comment]
@karlbrown-va

**Comment by karlbrown-va** [comment]
I think this needs to fix the test case as well- but I do like the improvement
As you are doing this, we may want to tack on the 'context' field as well.

**Comment by michael-barlow3** [comment]
Thanks, and yea working on adding context and notes as we speak.
I'll also update the test case next

Thank you
Mike Barlow
Technical Architect
Clinical Ancillary Product Line
EPMO Health Portfolio PMO/TM

Lancaster, Pa
(732) 682-8226 | M-F 8:30-5:00pm ET
***@***.******@***.***>
***@***.******@***.***>

From: Karl Brown ***@***.***>
Sent: Friday, May 14, 2021 12:47 PM
To: department-of-veterans-affairs/wtf-bot ***@***.***>
Cc: Barlow, Michael W. (GovernmentCIO) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/wtf-bot] Addresses Issue #11 (#13)


I think this needs to fix the test case as well- but I do like the improvement
As you are doing this, we may want to tack on the 'context' field as well.

-

**Comment by michael-barlow3** [comment]
@karlbrown-va - See newest PR #15

**Comment by karlbrown-va** [comment]
I assume the latest PR includes these changes so can we close this PR @michael-barlow3 ?

**Comment by michael-barlow3** [comment]
> I assume the latest PR includes these changes so can we close this PR @michael-barlow3 ?

Yep PR #15 contains all the latest and greatest changes including the ones from this PR.
Please close this PR.
Thanks

**Pull request closed without merging**
